'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18033
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Namespace XPInstantFeedback.Properties

    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")>
    Friend NotInheritable Partial Class Settings
        Inherits Global.System.Configuration.ApplicationSettingsBase

        Private Shared defaultInstance As XPInstantFeedback.Properties.Settings = CType((Global.System.Configuration.ApplicationSettingsBase.Synchronized(New XPInstantFeedback.Properties.Settings())), XPInstantFeedback.Properties.Settings)

        Public Shared ReadOnly Property [Default] As Settings
            Get
                Return XPInstantFeedback.Properties.Settings.defaultInstance
            End Get
        End Property

        <Global.System.Configuration.ApplicationScopedSettingAttribute()>
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>
        <Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString)>
        <Global.System.Configuration.DefaultSettingValueAttribute("Data Source=(local);Initial Catalog=Northwind;Integrated Security=True")>
        Public ReadOnly Property NorthwindConnectionString As String
            Get
                Return(CStr((Me("NorthwindConnectionString"))))
            End Get
        End Property
    End Class
End Namespace
